#!/bin/bash
# ==============================================================================
# ZAPFLOW AI — SSL SETUP (Let's Encrypt + Certbot)
# Usage: bash enable-ssl.sh your-domain.com admin@your-domain.com
# ==============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR" || exit 1

DOMAIN="${1:-}"
EMAIL="${2:-}"
ENV_FILE="$SCRIPT_DIR/.env.production"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.production.yml"
NGINX_TEMPLATE="$SCRIPT_DIR/infrastructure/nginx/nginx.conf.template"
NGINX_CONF="$SCRIPT_DIR/infrastructure/nginx/nginx.conf"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "${GREEN}[✔] $1${NC}"; }
warn() { echo -e "${YELLOW}[⚠] $1${NC}"; }
err()  { echo -e "${RED}[✖] $1${NC}"; }
step() { echo -e "\n${CYAN}━━━ $1 ━━━${NC}"; }
dc()   { docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"; }

if [ -z "$DOMAIN" ] || [ -z "$EMAIL" ]; then
    echo ""
    echo "Usage: bash enable-ssl.sh <domain> <email>"
    echo "Example: bash enable-ssl.sh zapflow.app admin@zapflow.app"
    echo ""
    exit 1
fi

echo ""
echo "============================================================"
echo -e "${CYAN}  ZAPFLOW AI — SSL SETUP${NC}"
echo "  Domain: $DOMAIN"
echo "  Email: $EMAIL"
echo "============================================================"

# ──────────────────────────────────────────────────────────────
step "1. VERIFY DNS"
# ──────────────────────────────────────────────────────────────
DNS_IP=$(dig +short "$DOMAIN" 2>/dev/null | tail -1 || nslookup "$DOMAIN" 2>/dev/null | grep -A1 "Name:" | grep "Address:" | awk '{print $2}' || true)
PUBLIC_IP=$(curl -4 -s --max-time 5 ifconfig.me 2>/dev/null || echo "unknown")

echo "  DNS resolves to: $DNS_IP"
echo "  VPS public IP:   $PUBLIC_IP"

if [ "$DNS_IP" != "$PUBLIC_IP" ]; then
    warn "DNS ($DNS_IP) does not match VPS IP ($PUBLIC_IP)"
    warn "Make sure $DOMAIN points to $PUBLIC_IP in your DNS panel"
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Cancelled. Fix DNS first."
        exit 0
    fi
fi
log "DNS check complete."

# ──────────────────────────────────────────────────────────────
step "2. ENSURE HTTP IS WORKING"
# ──────────────────────────────────────────────────────────────
HTTP_CHECK=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "http://$DOMAIN" 2>/dev/null || echo "000")
if [ "$HTTP_CHECK" = "200" ]; then
    log "HTTP accessible (200 OK)"
else
    err "HTTP not accessible ($HTTP_CHECK). Ensure nginx is running."
    exit 1
fi

# ──────────────────────────────────────────────────────────────
step "3. REQUEST CERTIFICATE"
# ──────────────────────────────────────────────────────────────

# Ensure certbot directories exist
mkdir -p /etc/letsencrypt /var/www/certbot

# Request certificate via the certbot container
dc run --rm certbot certonly \
    --webroot -w /var/www/certbot \
    -d "$DOMAIN" \
    --email "$EMAIL" \
    --agree-tos \
    --non-interactive \
    --force-renewal

if [ ! -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]; then
    err "Certificate not found after certbot run"
    exit 1
fi
log "SSL certificate obtained for $DOMAIN"

# ──────────────────────────────────────────────────────────────
step "4. ENABLE HTTPS IN DOCKER-COMPOSE"
# ──────────────────────────────────────────────────────────────
# Uncomment port 443 in docker-compose
if grep -q '# - "443:443"' "$COMPOSE_FILE"; then
    sed -i 's|# - "443:443"|- "443:443"|' "$COMPOSE_FILE"
    log "Port 443 enabled in docker-compose"
fi

# ──────────────────────────────────────────────────────────────
step "5. UPDATE NGINX FOR HTTPS"
# ──────────────────────────────────────────────────────────────
BACKEND_SERVICE=$(docker compose -f "$COMPOSE_FILE" config --services 2>/dev/null | grep -E 'backend|api|server' | head -n1 || echo "backend")
export BACKEND_SERVICE

# Generate HTTPS nginx config
cat > "$NGINX_CONF" <<SSLEOF
# ZAPFLOW AI — Production Nginx (HTTPS + WSS)
# Auto-generated by enable-ssl.sh for $DOMAIN

# Rate limiting
limit_req_zone \$binary_remote_addr zone=api_limit:10m rate=30r/s;
limit_req_zone \$binary_remote_addr zone=auth_limit:10m rate=5r/s;

upstream zapflow_backend {
    server ${BACKEND_SERVICE}:4025;
    keepalive 16;
}

# HTTP → HTTPS redirect
server {
    listen 80;
    server_name $DOMAIN;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

# HTTPS server
server {
    listen 443 ssl http2;
    server_name $DOMAIN;

    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

    # SSL settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

    # HSTS
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;

    root /usr/share/nginx/html;
    index index.html;

    # Compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;
    gzip_min_length 256;
    gzip_vary on;
    gzip_comp_level 6;
    gzip_proxied any;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    client_max_body_size 25M;

    # SPA
    location / {
        try_files \$uri \$uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
        add_header Pragma "no-cache" always;
    }

    # API
    location /api/ {
        limit_req zone=api_limit burst=60 nodelay;
        proxy_pass http://zapflow_backend;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Connection "";
    }

    # Auth
    location /auth/ {
        limit_req zone=auth_limit burst=10 nodelay;
        proxy_pass http://zapflow_backend;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # System
    location /system/ {
        proxy_pass http://zapflow_backend;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # Health probes
    location = /health { proxy_pass http://zapflow_backend; proxy_http_version 1.1; proxy_set_header Host \$host; }
    location = /ready { proxy_pass http://zapflow_backend; proxy_http_version 1.1; proxy_set_header Host \$host; }
    location = /status-whatsapp { proxy_pass http://zapflow_backend; proxy_http_version 1.1; proxy_set_header Host \$host; }
    location = /session-status { proxy_pass http://zapflow_backend; proxy_http_version 1.1; proxy_set_header Host \$host; }
    location = /sessions { proxy_pass http://zapflow_backend; proxy_http_version 1.1; proxy_set_header Host \$host; }
    location = /diagnostics { proxy_pass http://zapflow_backend; proxy_http_version 1.1; proxy_set_header Host \$host; }
    location = /metrics { proxy_pass http://zapflow_backend; proxy_http_version 1.1; proxy_set_header Host \$host; }
    location = /connections { proxy_pass http://zapflow_backend; proxy_http_version 1.1; proxy_set_header Host \$host; }

    # WebSocket (WSS)
    location /socket.io/ {
        proxy_pass http://zapflow_backend/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
        proxy_buffering off;
        proxy_cache off;
    }

    # Message/Media
    location /send-message { limit_req zone=api_limit burst=20 nodelay; proxy_pass http://zapflow_backend; proxy_http_version 1.1; proxy_set_header Host \$host; proxy_set_header X-Real-IP \$remote_addr; proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto \$scheme; }
    location /send-media { limit_req zone=api_limit burst=10 nodelay; proxy_pass http://zapflow_backend; proxy_http_version 1.1; proxy_set_header Host \$host; proxy_set_header X-Real-IP \$remote_addr; proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto \$scheme; client_max_body_size 50M; proxy_read_timeout 120s; }

    # Session routes
    location /sessions/ { proxy_pass http://zapflow_backend; proxy_http_version 1.1; proxy_set_header Host \$host; proxy_set_header X-Real-IP \$remote_addr; proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto \$scheme; }
    location /session/ { proxy_pass http://zapflow_backend; proxy_http_version 1.1; proxy_set_header Host \$host; proxy_set_header X-Real-IP \$remote_addr; proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto \$scheme; }

    # Static assets
    location ~* \.(?:js|css|woff2|woff|ttf)\$ { expires 365d; add_header Cache-Control "public, immutable, max-age=31536000" always; }
    location ~* \.(?:png|ico|svg|webp|jpg|jpeg|gif|avif)\$ { expires 30d; add_header Cache-Control "public, max-age=2592000" always; }
}
SSLEOF

log "HTTPS nginx config generated."

# ──────────────────────────────────────────────────────────────
step "6. UPDATE .env.production"
# ──────────────────────────────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
    sed -i "s|^DOMAIN=.*|DOMAIN=$DOMAIN|" "$ENV_FILE"
    sed -i "s|^LETSENCRYPT_EMAIL=.*|LETSENCRYPT_EMAIL=$EMAIL|" "$ENV_FILE"
    sed -i "s|^FRONTEND_URL=.*|FRONTEND_URL=https://$DOMAIN|" "$ENV_FILE"

    CURRENT_CORS=$(grep "^CORS_ALLOWED_ORIGINS=" "$ENV_FILE" | cut -d'=' -f2- || true)
    if ! echo "$CURRENT_CORS" | grep -q "https://$DOMAIN"; then
        sed -i "s|^CORS_ALLOWED_ORIGINS=.*|CORS_ALLOWED_ORIGINS=https://$DOMAIN,http://$DOMAIN,$CURRENT_CORS|" "$ENV_FILE"
    fi
    log ".env.production updated with HTTPS URLs"
fi

# ──────────────────────────────────────────────────────────────
step "7. RESTART SERVICES"
# ──────────────────────────────────────────────────────────────
dc restart nginx
dc restart backend
log "Services restarted."

sleep 5

HTTPS_CHECK=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "https://$DOMAIN" 2>/dev/null || echo "000")
if [ "$HTTPS_CHECK" = "200" ]; then
    echo ""
    echo "============================================================"
    echo -e "${GREEN}  ✨ SSL ENABLED SUCCESSFULLY ✨${NC}"
    echo "============================================================"
    echo -e "  HTTPS:     ${CYAN}https://$DOMAIN${NC}"
    echo -e "  WSS:       ${CYAN}wss://$DOMAIN/socket.io/${NC}"
    echo -e "  API:       ${CYAN}https://$DOMAIN/api/health${NC}"
    echo "============================================================"
else
    err "HTTPS check returned $HTTPS_CHECK"
    echo "  Check: docker logs zapai-nginx --tail=20"
fi
