const express = require('express');
const router = express.Router();
const aiController = require('../controllers/aiController');

router.post('/ai/enable', aiController.enable);
router.post('/ai/disable', aiController.disable);
router.post('/ai/toggle', aiController.toggle);
router.get('/ai/status', aiController.status);
router.get('/ai/prompt', aiController.getPrompt);
router.post('/ai/prompt', aiController.savePrompt);
router.get('/ai/learning/dashboard', aiController.learningDashboard);
router.post('/ai/learning/analyze', aiController.runLearningAnalysis);
router.post('/ai/learning/:id/apply', aiController.applyLearningSuggestion);
router.put('/ai/learning/:id', aiController.editLearningSuggestion);
router.post('/ai/learning/:id/ignore', aiController.ignoreLearningSuggestion);
router.get('/ai/prompt-history', aiController.promptHistory);
router.get('/ai/project-analyze', aiController.projectAnalyze);
router.get('/ai/architecture-map', aiController.architectureMap);
router.get('/ai/architect/full-scan', aiController.architectFullScan);
router.get('/ai/copilot-super-prompt', aiController.copilotSuperPrompt);
router.get('/ai/ui-analyze', aiController.uiAnalyze);
router.get('/ai/feature-roadmap', aiController.featureRoadmap);
router.get('/ai/system-health', aiController.systemHealth);
router.get('/ai/system-diagnostics', aiController.systemDiagnostics);
router.get('/ai/system-status', aiController.systemStatus);
router.get('/ai/system-registry', aiController.systemRegistry);
router.get('/ai/project-status', aiController.projectStatus);
router.post('/ai/pipeline/refresh', aiController.pipelineRefresh);
router.get('/ai/pipeline', aiController.pipelineList);
router.post('/ai/replicate-page', aiController.replicateProjectPage);
router.post('/ai/page-loop', aiController.generateProjectPages);
router.post('/ai/doc-analyze', aiController.analyzeProjectDoc);
router.post('/ai/chat', aiController.assistantChat);
router.post('/ai/assistant/command', aiController.assistantCommand);
router.post('/ai/reply', aiController.reply);
router.post('/ai/dev-core/task', aiController.runDevCoreTask);
router.post('/ai/fix-system-issues', aiController.fixSystemIssues);
router.post('/ai/create-feature', aiController.createFeature);
router.post('/ai/create-module', aiController.createModule);
router.post('/ai/generate/fullstack-module', aiController.generateFullstackModule);
router.post('/ai/generate/full-pages', aiController.generateFullPages);
router.get('/ai/code-curation', aiController.codeCuration);
router.post('/ai/run-tests', aiController.runAITests);
router.post('/ai/log-error', aiController.logFrontendError);
router.get('/ai/error-logs', aiController.getFrontendErrorLogs);

module.exports = router;
