module.exports = {
  activationConfirmationService: require('../../services/activationConfirmationService'),
  activationLoggerService: require('../../services/activationLoggerService'),
  aiConfigService: require('../../services/aiConfigService'),
  aiDiagnosticsService: require('../../services/aiDiagnosticsService'),
  aiLearningEngine: require('../../services/aiLearningEngine'),
  aiResponseEngine: require('../../services/aiResponseEngine'),
  analyticsService: require('../../services/analyticsService'),
  automationService: require('../../services/automationService'),
  campaignEngine: require('../../services/campaignEngine'),
  campaignRuntime: require('../../services/campaignRuntime'),
  campaignService: require('../../services/campaignService'),
  contactsService: require('../../services/contactsService'),
  leadsService: require('../../services/leadsService'),
  messageService: require('../../services/messageService'),
  messagingService: require('../../services/messagingService'),
  sessionManager: require('../../services/sessionManager'),
  systemManager: require('../../services/systemManager'),
  webhookService: require('../../services/webhookService'),
  whatsappService: require('../../services/whatsappService'),
};
