module.exports = {
  acebot: require('../../routes/acebot'),
  ai: require('../../routes/ai'),
  aiConfig: require('../../routes/aiConfig'),
  aiGeneratedFixes: require('../../routes/aiGeneratedFixes'),
  analytics: require('../../routes/analytics'),
  automation: require('../../routes/automation'),
  contacts: require('../../routes/contacts'),
  conversations: require('../../routes/conversations'),
  integrations: require('../../routes/integrations'),
  leads: require('../../routes/leads'),
  messages: require('../../routes/messages'),
  sessions: require('../../routes/sessions'),
  system: require('../../routes/system'),
};
