# ZAPAI Install Library — env.sh
# Directory setups, environment generation, backend build, migrations, frontend build.

generate_env() {
  step "8. ENVIRONMENT FILE (.env.production)"
  
  if ! id "$APP_USER" >/dev/null 2>&1; then
    useradd -m -s /bin/bash "$APP_USER"
    log "User '$APP_USER' created"
  fi

  local dir
  for dir in \
    "$APP_DIR" \
    "$LOGS_DIR/backend" \
    "$LOGS_DIR/deploy" \
    "$LOGS_DIR/nginx" \
    "$APP_DIR/backups/postgres" \
    "$APP_DIR/backups/sessions" \
    "$RELEASES_DIR/timestamps" \
    "$RELEASES_DIR/current" \
    "$RELEASES_DIR/previous"; do
    mkdir -p "$dir"
  done
  chown -R "$APP_USER:$APP_USER" "$APP_DIR"
  log "Directories created"

  if [ -d "$APP_DIR/.git" ]; then
    log "Repository already at $APP_DIR — pulling latest"
    sudo -u "$APP_USER" git -C "$APP_DIR" fetch origin main --quiet 2>/dev/null || true
    sudo -u "$APP_USER" git -C "$APP_DIR" reset --hard origin/main 2>/dev/null || true
  elif [ -d "/opt/ZAPAI-FINAL/.git" ]; then
    cp -r /opt/ZAPAI-FINAL/. "$APP_DIR/"
    chown -R "$APP_USER:$APP_USER" "$APP_DIR"
    warn "Copied from /opt/ZAPAI-FINAL"
  else
    log "Cloning $REPO_URL → $APP_DIR"
    sudo -u "$APP_USER" git clone "$REPO_URL" "$APP_DIR" 2>&1 | tail -5
    log "Repository cloned"
  fi

  local ENV_FILE="$APP_DIR/.env.production"
  
  if [ -f "$ENV_FILE" ]; then
    log ".env.production already exists — refreshing variables"
    local existing_jwt
    existing_jwt=$(grep '^JWT_SECRET=' "$ENV_FILE" 2>/dev/null | cut -d= -f2 || echo "")
    local existing_session
    existing_session=$(grep '^SESSION_SECRET=' "$ENV_FILE" 2>/dev/null | cut -d= -f2 || echo "")
    local existing_enc
    existing_enc=$(grep '^ENCRYPTION_KEY=' "$ENV_FILE" 2>/dev/null | cut -d= -f2 || echo "")
    [ -n "$existing_jwt" ] && JWT_SECRET="$existing_jwt"
    [ -n "$existing_session" ] && SESSION_SECRET="$existing_session"
    [ -n "$existing_enc" ] && ENCRYPTION_KEY="$existing_enc"
    rm -f "$ENV_FILE"
  fi

  [ -z "${JWT_SECRET:-}" ] && JWT_SECRET="$(openssl rand -hex 32)"
  [ -z "${SESSION_SECRET:-}" ] && SESSION_SECRET="$(openssl rand -hex 32)"
  [ -z "${ENCRYPTION_KEY:-}" ] && ENCRYPTION_KEY="$(openssl rand -hex 32)"

  cat > "$ENV_FILE" <<ENVEOF
# ZAPAI-FINAL Production Environment
# Auto-generated by deploy/install.sh on $(date)
# IP: ${PUBLIC_IP} | URL: ${PUBLIC_URL}
# Do NOT commit this file to git.

NODE_ENV=production
PORT=${BACKEND_PORT}
HOST=0.0.0.0

# Single source of truth for CORS and Socket.IO
APP_PUBLIC_URL=${PUBLIC_URL}

# PostgreSQL (Standard)
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_USER=zapai
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=zapai_crm
DATABASE_URL=postgresql://zapai:${DB_PASS}@localhost:5432/zapai_crm

# PostgreSQL (Legacy/Alternative Aliases)
DB_HOST=localhost
DB_PORT=5432
DB_USER=zapai
DB_PASSWORD=${DB_PASS}
DB_NAME=zapai_crm

# Redis
REDIS_URL=redis://localhost:6379

# Auth
JWT_SECRET=${JWT_SECRET}
AUTH_JWT_SECRET=${JWT_SECRET}
SESSION_SECRET=${SESSION_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
JWT_EXPIRES_IN=7d

# URLs
APP_URL=${PUBLIC_URL}
PUBLIC_URL=${PUBLIC_URL}
BACKEND_URL=http://${PUBLIC_IP}:4025
FRONTEND_URL=${PUBLIC_URL}
CORS_ALLOWED_ORIGINS=${PUBLIC_URL}
ALLOWED_ORIGINS=${PUBLIC_URL}
CORS_ORIGIN=${PUBLIC_URL}

# Admin Default Credentials
AUTH_DEFAULT_USERNAME=${ADMIN_USERNAME}
AUTH_DEFAULT_EMAIL=${ADMIN_EMAIL}
AUTH_DEFAULT_PASSWORD=${ADMIN_PASSWORD}
AUTH_DEFAULT_ROLE=master
AUTH_DEFAULT_TENANT_ID=default

# App Features
DEFAULT_COMPANY_ID=default
NODE_ROLE=master
MASTER=true
FEATURE_ADMIN_MASTER=true
FEATURE_NODE_MASTER_API=true
FEATURE_NODE_AUTO_REGISTER=false

# PM2
PM2_READY_SIGNAL=true
HEALTH_CHECK_INTERVAL_MS=60000

# Logging
LOG_LEVEL=info
CRASH_EXIT_ON_UNHANDLED=true

# Optional
AI_MEMORY_ENABLED=true
ENVEOF

  chown "$APP_USER:$APP_USER" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  log ".env.production created/updated (IP: ${PUBLIC_IP}, admin: ${ADMIN_USERNAME})"

  local FRONTEND_ENV="$FRONTEND_DIR/.env.production"
  if [ -d "$FRONTEND_DIR" ]; then
    echo "VITE_API_URL=/" > "$FRONTEND_ENV"
    chown "$APP_USER:$APP_USER" "$FRONTEND_ENV" 2>/dev/null || true
    log "frontend-official/.env.production: VITE_API_URL=/ (nginx proxies /api)"
  fi
}

install_backend() {
  step "9. BACKEND DEPENDENCIES"
  if [ -d "$BACKEND_DIR" ]; then
    cd "$BACKEND_DIR"
    if [ -d node_modules ] && [ ! -f node_modules/.install_ok ]; then
      warn "Removing possibly broken node_modules..."
      rm -rf node_modules
    fi
    sudo -u "$APP_USER" npm install \
      --production \
      --legacy-peer-deps \
      --prefer-offline \
      --no-audit \
      --no-fund 2>&1 | tail -5
    touch node_modules/.install_ok 2>/dev/null || true
    log "Backend deps installed"
  else
    err "backend/ not found at $BACKEND_DIR — clone may have failed"
  fi
}

run_migrations() {
  step "10. DATABASE MIGRATIONS"
  if [ -f "$BACKEND_DIR/scripts/run-migrations.js" ]; then
    cd "$BACKEND_DIR"

    if [ -f "$APP_DIR/.env.production" ]; then
      set -a
      # shellcheck disable=SC1091
      source "$APP_DIR/.env.production" 2>/dev/null || true
      set +a
    fi

    log "Testando conexão real utilizando a URL de conexão..."
    if ! PGPASSWORD="${POSTGRES_PASSWORD:-}" psql "$DATABASE_URL" -c 'SELECT 1' >/dev/null 2>&1; then
      err "Falha ao conectar usando a DATABASE_URL: $DATABASE_URL. Verifique as credenciais no arquivo .env.production."
    fi
    log "✔ Conexão real com DATABASE_URL validada com sucesso! (SELECT 1 ok)"

    log "Executando migrations no banco de dados..."
    if ! sudo -u "$APP_USER" bash -c \
        "set -a; source '$APP_DIR/.env.production' 2>/dev/null; set +a; NODE_ENV=production node scripts/run-migrations.js"; then
      err "Migrations FALHARAM! O comando de migração falhou. Verifique os erros acima e o stack de execução."
    fi
    log "✔ Migrations executadas com sucesso!"
  else
    warn "run-migrations.js não encontrado — pulando etapa de migrations"
  fi

  step "10.5. ADMIN MASTER SEED (zapadmin / zapadmin1010)"
  cd "$BACKEND_DIR"
  if [ -f "$BACKEND_DIR/scripts/seed-admin.js" ]; then
    if ! sudo -u "$APP_USER" bash -c \
        "set -a; source '$APP_DIR/.env.production' 2>/dev/null; set +a; \
         AUTH_DEFAULT_USERNAME=zapadmin \
         AUTH_DEFAULT_PASSWORD=zapadmin1010 \
         AUTH_DEFAULT_EMAIL=zapadmin@zapai.local \
         AUTH_DEFAULT_ROLE=master \
         AUTH_DEFAULT_TENANT_ID=default \
         NODE_ENV=production \
         node scripts/seed-admin.js" 2>&1 | tail -8; then
      warn "Admin seed failed — login may require manual setup"
    else
      log "Admin user ready: zapadmin / zapadmin1010 ✔"
    fi
  else
    warn "seed-admin.js not found — admin user not auto-created"
  fi
}

build_frontend() {
  step "11. FRONTEND BUILD"
  if [ -d "$FRONTEND_DIR" ]; then
    cd "$FRONTEND_DIR"
    rm -rf dist 2>/dev/null || true

    sudo -u "$APP_USER" npm install \
      --legacy-peer-deps \
      --prefer-offline \
      --no-audit \
      --no-fund 2>&1 | tail -5

    if ! sudo -u "$APP_USER" bash -c \
        "NODE_ENV=production VITE_API_URL=/ npx vite build --outDir dist" 2>&1 | tail -10; then
      err "Frontend build FAILED — aborting install. Fix build errors and retry."
    fi

    if [ -f "$FRONTEND_DIR/dist/index.html" ]; then
      local chunks
      chunks=$(find "$FRONTEND_DIR/dist/assets" -name '*.js' 2>/dev/null | wc -l)
      log "Frontend built: $chunks JS chunks ✔"
    else
      err "dist/index.html missing after build — unexpected failure"
    fi
  else
    err "frontend-official/ not found — clone may have failed"
  fi
}
